
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
  const lastUpdatedDate = "October 26, 2023"; // Replace with actual last updated date
  const companyName = "Caffico Express"; // Replace with your actual company name
  const websiteUrl = "https://www.caffico.com"; // Replace with your actual website URL
  const contactEmail = "privacy@caffico.com"; // Replace with your actual contact email

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      <main className="flex-grow container mx-auto px-4 py-8">
         <div className="max-w-3xl mx-auto">
            <Button asChild variant="outline" className="mb-6">
              <Link href="/">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Home
              </Link>
            </Button>
          <Card className="shadow-lg rounded-xl">
            <CardHeader>
              <CardTitle className="text-3xl font-bold text-primary">Privacy Policy</CardTitle>
              <CardDescription>Last updated: {lastUpdatedDate}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6 prose prose-sm sm:prose-base max-w-none dark:prose-invert">
              <p>
                Welcome to {companyName} ("us", "we", or "our"). We operate the website {websiteUrl} (hereinafter referred to as the "Service").
                Our Privacy Policy governs your visit to {websiteUrl}, and explains how we collect, safeguard and disclose information that results from your use of our Service.
              </p>
              <p>
                We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">1. Definitions</h2>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li><strong>Service</strong> means the {websiteUrl} website operated by {companyName}.</li>
                <li><strong>Personal Data</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                <li><strong>Usage Data</strong> is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Cookies</strong> are small files stored on your device (computer or mobile device).</li>
              </ul>

              <h2 className="text-2xl font-semibold mt-8 mb-3">2. Information Collection and Use</h2>
              <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
              
              <h3 className="text-xl font-semibold mt-4 mb-2">Types of Data Collected</h3>
              <h4 className="text-lg font-medium mt-3 mb-1">Personal Data</h4>
              <p>
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City (for order delivery if applicable)</li>
                <li>Cookies and Usage Data</li>
                <li>Payment information (processed by third-party payment processors like Razorpay)</li>
              </ul>

              <h4 className="text-lg font-medium mt-3 mb-1">Usage Data</h4>
              <p>
                We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
                This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>

              <h4 className="text-lg font-medium mt-3 mb-1">Tracking & Cookies Data</h4>
              <p>
                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                Cookies are files with a small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be ableable to use some portions of our Service.
              </p>
              <p>Examples of Cookies we use:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
              </ul>


              <h2 className="text-2xl font-semibold mt-8 mb-3">3. Use of Data</h2>
              <p>{companyName} uses the collected data for various purposes:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li>To provide and maintain our Service;</li>
                <li>To notify you about changes to our Service;</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so;</li>
                <li>To provide customer support;</li>
                <li>To gather analysis or valuable information so that we can improve our Service;</li>
                <li>To monitor the usage of our Service;</li>
                <li>To detect, prevent and address technical issues;</li>
                <li>To fulfill the purpose for which you provide it, such as processing your orders.</li>
              </ul>

              <h2 className="text-2xl font-semibold mt-8 mb-3">4. Retention of Data</h2>
              <p>
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">5. Transfer of Data</h2>
              <p>
                Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
              </p>
              
              <h2 className="text-2xl font-semibold mt-8 mb-3">6. Disclosure of Data</h2>
              <p>We may disclose Personal Data that we collect, or you provide:</p>
               <ul className="list-disc list-inside space-y-1 pl-4">
                <li><strong>Disclosure for Law Enforcement.</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
                <li><strong>Business Transaction.</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
               </ul>

              <h2 className="text-2xl font-semibold mt-8 mb-3">7. Security of Data</h2>
              <p>
                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">8. Your Data Protection Rights</h2>
              <p>
                Depending on your location, you may have certain data protection rights. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at {contactEmail}.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">9. Service Providers</h2>
              <p>
                We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. One such provider is Razorpay for payment processing. Their Privacy Policy can be viewed on their website.
              </p>
              
              <h2 className="text-2xl font-semibold mt-8 mb-3">10. Children's Privacy</h2>
              <p>
                Our Service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">11. Changes to This Privacy Policy</h2>
              <p>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "last updated" date at the top of this Privacy Policy.
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-3">12. Contact Us</h2>
              <p>If you have any questions about this Privacy Policy, please contact us:</p>
              <p>By email: {contactEmail}</p>

              <p className="mt-8 text-sm text-muted-foreground">
                <strong>Disclaimer:</strong> This is a template Privacy Policy. You should consult with a legal professional to ensure this policy is adequate for your specific business needs and complies with all applicable laws and regulations.
              </p>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  );
}
